domservices:
  krayin-mysql:
    image: percona/percona-server:latest
    container_name: krayin-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TZ=America/Sao_Paulo
    networks:
      - network_public
    #ports:
      #- 3306:3306
    volumes:
      - krayin_mysql_data:/var/lib/mysql
      - /home/deploy/krayin-crm/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    deploy:
      placement:
        constraints:
          - node.role == manager
          #- node.hostname == worker1
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--sql-mode=",
        "--default-authentication-plugin=mysql_native_password",
        "--max-allowed-packet=512MB",
        "--expire_logs_days=7",
        "--max_binlog_size=100M"		
      ]
      
  krayin-redis:
    image: redis:7-alpine
    container_name: krayin-redis
    networks:
      - network_public
    deploy:
      placement:
        constraints:
          - node.role == manager	

########################

# Entrar no conteiner do krayin e executar

# Editar a logo em /var/lib/docker/volumes/krayin_data/_data/laravel-crm/public/admin/build/assets

# Substitua os arquivos: logo-0db24d41.svg e o favicon: favicon-a99d4e55.ico

########################

  krayin-crm:
    image: krayin-crm-arm64
    container_name: krayin-crm
    volumes:
      - krayin_data:/var/www/html/
      - /home/deploy/krayin.env:/var/www/html/krayin/.env   # <-- Monte seu .env local aqui
    #ports:
    #  - 2020:80
    networks:
      - network_public
    environment:
      - krayin_PUBLIC_URL=https://krayincrm.seudominio.com # colocar o dominio correto.
      - krayin_CADDY_ADDRESSES=:80
      - DB_HOST=krayin-mysql
      - DB_USERNAME=root
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.krayin.rule=Host(`krayincrm.seudominio.com`)" # colocar o dominio correto.
      - "traefik.http.routers.krayin.entrypoints=websecure"
      - "traefik.http.routers.krayin.tls=true"
      - "traefik.http.routers.krayin.tls.certresolver=leresolver"
      - "traefik.http.services.krayin.loadbalancer.server.port=80"
      - "traefik.http.middlewares.krayin-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.krayin.middlewares=krayin-headers"

volumes:
  krayin_mysql_data:
    external: true
    name: krayin_mysql_data
  krayin_data:
    external: true
    name: krayin_data

networks:
  network_public:
    external: true
    name: network_public
